// Generated by CIRCT firtool-1.138.0
module AxiLiteMem32Test(	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7
  input         clock,	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7
                reset,	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7
  input  [23:0] io_axi_awaddr,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  input         io_axi_awvalid,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  output        io_axi_awready,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  input  [31:0] io_axi_wdata,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  input  [3:0]  io_axi_wstrb,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  input         io_axi_wvalid,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  output        io_axi_wready,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  output [1:0]  io_axi_bresp,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  output        io_axi_bvalid,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  input         io_axi_bready,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  input  [23:0] io_axi_araddr,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  input         io_axi_arvalid,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  output        io_axi_arready,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  output [31:0] io_axi_rdata,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  output [1:0]  io_axi_rresp,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  output        io_axi_rvalid,	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
  input         io_axi_rready	// src/main/scala/pca/AxiLiteMem32Test.scala:38:14
);

  wire [31:0] _mem_ext_R0_data;	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
  reg         awHoldValid;	// src/main/scala/pca/AxiLiteMem32Test.scala:50:28
  reg  [23:0] awHoldAddr;	// src/main/scala/pca/AxiLiteMem32Test.scala:51:24
  reg         wHoldValid;	// src/main/scala/pca/AxiLiteMem32Test.scala:52:28
  reg  [31:0] wHoldData;	// src/main/scala/pca/AxiLiteMem32Test.scala:53:24
  reg  [3:0]  wHoldStrb;	// src/main/scala/pca/AxiLiteMem32Test.scala:54:24
  reg         bvalid;	// src/main/scala/pca/AxiLiteMem32Test.scala:55:28
  wire        io_axi_awready_0 = ~awHoldValid & ~bvalid;	// src/main/scala/pca/AxiLiteMem32Test.scala:50:28, :55:28, :57:{21,34,37}
  wire        io_axi_wready_0 = ~wHoldValid & ~bvalid;	// src/main/scala/pca/AxiLiteMem32Test.scala:52:28, :55:28, :57:37, :58:{21,34}
  wire        doWrite = awHoldValid & wHoldValid & ~bvalid;	// src/main/scala/pca/AxiLiteMem32Test.scala:50:28, :52:28, :55:28, :57:37, :73:{29,43}
  reg         rvalid;	// src/main/scala/pca/AxiLiteMem32Test.scala:95:23
  reg  [31:0] rdata;	// src/main/scala/pca/AxiLiteMem32Test.scala:96:19
  wire        arFire = io_axi_arvalid & ~rvalid;	// src/main/scala/pca/AxiLiteMem32Test.scala:95:23, :98:17, :100:31
  reg         rvalidPipe;	// src/main/scala/pca/AxiLiteMem32Test.scala:105:27
  reg  [31:0] memReadData;	// src/main/scala/pca/AxiLiteMem32Test.scala:106:28
  wire        awFire = io_axi_awvalid & io_axi_awready_0;	// src/main/scala/pca/AxiLiteMem32Test.scala:57:34, :60:31
  wire        wFire = io_axi_wvalid & io_axi_wready_0;	// src/main/scala/pca/AxiLiteMem32Test.scala:58:34, :61:31
  wire        rFire = rvalid & io_axi_rready;	// src/main/scala/pca/AxiLiteMem32Test.scala:95:23, :108:22
  always @(posedge clock) begin	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7
    if (reset) begin	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7
      awHoldValid <= 1'h0;	// src/main/scala/pca/AxiLiteMem32Test.scala:50:28
      wHoldValid <= 1'h0;	// src/main/scala/pca/AxiLiteMem32Test.scala:52:28
      bvalid <= 1'h0;	// src/main/scala/pca/AxiLiteMem32Test.scala:55:28
      rvalid <= 1'h0;	// src/main/scala/pca/AxiLiteMem32Test.scala:95:23
      rvalidPipe <= 1'h0;	// src/main/scala/pca/AxiLiteMem32Test.scala:105:27
    end
    else begin	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7
      awHoldValid <= ~doWrite & (awFire | awHoldValid);	// src/main/scala/pca/AxiLiteMem32Test.scala:50:28, :60:31, :63:16, :64:17, :73:{29,43}, :75:17, :84:17
      wHoldValid <= ~doWrite & (wFire | wHoldValid);	// src/main/scala/pca/AxiLiteMem32Test.scala:52:28, :61:31, :63:16, :67:15, :68:16, :73:{29,43}, :75:17, :84:17, :85:17
      bvalid <= ~(bvalid & io_axi_bready) & (doWrite | bvalid);	// src/main/scala/pca/AxiLiteMem32Test.scala:55:28, :73:{29,43}, :75:17, :83:17, :88:22, :89:{15,24}
      rvalid <= ~rFire & (rvalidPipe | rvalid);	// src/main/scala/pca/AxiLiteMem32Test.scala:95:23, :105:27, :108:22, :109:15, :110:12, :111:26, :112:12
      rvalidPipe <= arFire;	// src/main/scala/pca/AxiLiteMem32Test.scala:100:31, :105:27
    end
    if (awFire)	// src/main/scala/pca/AxiLiteMem32Test.scala:60:31
      awHoldAddr <= io_axi_awaddr;	// src/main/scala/pca/AxiLiteMem32Test.scala:51:24
    if (wFire) begin	// src/main/scala/pca/AxiLiteMem32Test.scala:61:31
      wHoldData <= io_axi_wdata;	// src/main/scala/pca/AxiLiteMem32Test.scala:53:24
      wHoldStrb <= io_axi_wstrb;	// src/main/scala/pca/AxiLiteMem32Test.scala:54:24
    end
    if (rFire | ~rvalidPipe) begin	// src/main/scala/pca/AxiLiteMem32Test.scala:96:19, :105:27, :108:22, :109:15, :111:26
    end
    else	// src/main/scala/pca/AxiLiteMem32Test.scala:96:19, :109:15, :111:26
      rdata <= memReadData;	// src/main/scala/pca/AxiLiteMem32Test.scala:96:19, :106:28
    memReadData <= _mem_ext_R0_data;	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24, :106:28
  end // always @(posedge)
  mem_128x32 mem_ext (	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
    .R0_addr (io_axi_araddr[8:2]),	// src/main/scala/pca/AxiLiteMem32Test.scala:46:{15,20}
    .R0_en   (arFire),	// src/main/scala/pca/AxiLiteMem32Test.scala:100:31
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .W0_addr (awHoldAddr[8:2]),	// src/main/scala/pca/AxiLiteMem32Test.scala:46:{15,20}, :51:24
    .W0_en   (doWrite),	// src/main/scala/pca/AxiLiteMem32Test.scala:73:{29,43}
    .W0_clk  (clock),
    .W0_data (wHoldData),	// src/main/scala/pca/AxiLiteMem32Test.scala:53:24
    .W0_mask (wHoldStrb)	// src/main/scala/pca/AxiLiteMem32Test.scala:54:24
  );	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
  assign io_axi_awready = io_axi_awready_0;	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7, :57:34
  assign io_axi_wready = io_axi_wready_0;	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7, :58:34
  assign io_axi_bresp = 2'h0;	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7, :92:17
  assign io_axi_bvalid = bvalid;	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7, :55:28
  assign io_axi_arready = ~rvalid;	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7, :95:23, :98:17
  assign io_axi_rdata = rdata;	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7, :96:19
  assign io_axi_rresp = 2'h0;	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7, :92:17
  assign io_axi_rvalid = rvalid;	// src/main/scala/pca/AxiLiteMem32Test.scala:37:7, :95:23
endmodule
