// Generated by CIRCT firtool-1.138.0
// VCS coverage exclude_file
module mem_128x32(	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
  input  [6:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [6:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data,
  input  [3:0]  W0_mask
);

  reg [31:0] Memory[0:127];	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
  reg        _R0_en_d0;	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
  reg [6:0]  _R0_addr_d0;	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
  always @(posedge R0_clk) begin	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
    _R0_en_d0 <= R0_en;	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
    _R0_addr_d0 <= R0_addr;	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
    if (W0_en & W0_mask[0])	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
      Memory[W0_addr][32'h0 +: 8] <= W0_data[7:0];	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
    if (W0_en & W0_mask[1])	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
      Memory[W0_addr][32'h8 +: 8] <= W0_data[15:8];	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
    if (W0_en & W0_mask[2])	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
      Memory[W0_addr][32'h10 +: 8] <= W0_data[23:16];	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
    if (W0_en & W0_mask[3])	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
      Memory[W0_addr][32'h18 +: 8] <= W0_data[31:24];	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 32'bx;	// src/main/scala/pca/AxiLiteMem32Test.scala:42:24
endmodule
