// Generated by CIRCT firtool-1.138.0
// VCS coverage exclude_file
module mem_2x32(	// src/main/scala/pca/SRAM1RW.scala:26:26
  input         R0_addr,
                R0_en,
                R0_clk,
  output [31:0] R0_data,
  input         W0_addr,
                W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:1];	// src/main/scala/pca/SRAM1RW.scala:26:26
  reg        _R0_en_d0;	// src/main/scala/pca/SRAM1RW.scala:26:26
  reg        _R0_addr_d0;	// src/main/scala/pca/SRAM1RW.scala:26:26
  always @(posedge R0_clk) begin	// src/main/scala/pca/SRAM1RW.scala:26:26
    _R0_en_d0 <= R0_en;	// src/main/scala/pca/SRAM1RW.scala:26:26
    _R0_addr_d0 <= R0_addr;	// src/main/scala/pca/SRAM1RW.scala:26:26
  end // always @(posedge)
  always @(posedge W0_clk) begin	// src/main/scala/pca/SRAM1RW.scala:26:26
    if (W0_en)	// src/main/scala/pca/SRAM1RW.scala:26:26
      Memory[W0_addr] <= W0_data;	// src/main/scala/pca/SRAM1RW.scala:26:26
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 32'bx;	// src/main/scala/pca/SRAM1RW.scala:26:26
endmodule


