// Generated by CIRCT firtool-1.138.0
module PCACompWithMMIO(	// src/main/scala/pca/PCACompWithMMIO.scala:14:7
  input         clock,	// src/main/scala/pca/PCACompWithMMIO.scala:14:7
                reset,	// src/main/scala/pca/PCACompWithMMIO.scala:14:7
  input  [31:0] io_mmio_addr,	// src/main/scala/pca/PCACompWithMMIO.scala:17:14
                io_mmio_wdata,	// src/main/scala/pca/PCACompWithMMIO.scala:17:14
  input         io_mmio_wen,	// src/main/scala/pca/PCACompWithMMIO.scala:17:14
  output [31:0] io_mmio_rdata	// src/main/scala/pca/PCACompWithMMIO.scala:17:14
);

  PCACompMMIOBridge bridge (	// src/main/scala/pca/PCACompWithMMIO.scala:15:22
    .clock         (clock),
    .reset         (reset),
    .io_mmio_addr  (io_mmio_addr),
    .io_mmio_wdata (io_mmio_wdata),
    .io_mmio_wen   (io_mmio_wen),
    .io_mmio_rdata (io_mmio_rdata)
  );	// src/main/scala/pca/PCACompWithMMIO.scala:15:22
endmodule


