// Generated by CIRCT firtool-1.138.0
module PCACompBlock_nrows2_ncols12_nblocks3_w4_pxbw5_iembw8_npcs2(	// src/main/scala/pca/PCACompBlock.scala:11:7
  input         clock,	// src/main/scala/pca/PCACompBlock.scala:11:7
                reset,	// src/main/scala/pca/PCACompBlock.scala:11:7
                io_rowid,	// src/main/scala/pca/PCACompBlock.scala:39:14
  input  [19:0] io_indata,	// src/main/scala/pca/PCACompBlock.scala:39:14
  input         io_indatavalid,	// src/main/scala/pca/PCACompBlock.scala:39:14
                io_out_ready,	// src/main/scala/pca/PCACompBlock.scala:39:14
  output        io_out_valid,	// src/main/scala/pca/PCACompBlock.scala:39:14
  output [31:0] io_out_bits,	// src/main/scala/pca/PCACompBlock.scala:39:14
  input         io_updateIEM,	// src/main/scala/pca/PCACompBlock.scala:39:14
                io_verifyIEM,	// src/main/scala/pca/PCACompBlock.scala:39:14
                io_iempos,	// src/main/scala/pca/PCACompBlock.scala:39:14
  input  [31:0] io_iemdata,	// src/main/scala/pca/PCACompBlock.scala:39:14
  output [31:0] io_iemdataverify	// src/main/scala/pca/PCACompBlock.scala:39:14
);

  wire        _outQ_io_enq_ready;	// src/main/scala/pca/PCACompBlock.scala:184:20
  wire [31:0] _mems_1_io_rdata;	// src/main/scala/pca/PCACompBlock.scala:70:11
  wire [31:0] _mems_0_io_rdata;	// src/main/scala/pca/PCACompBlock.scala:70:11
  reg  [19:0] indataHoldReg;	// src/main/scala/pca/PCACompBlock.scala:60:30
  reg         dataReceivedStageReg;	// src/main/scala/pca/PCACompBlock.scala:98:37
  reg  [12:0] multiplied_0_0;	// src/main/scala/pca/PCACompBlock.scala:126:23
  reg  [12:0] multiplied_0_1;	// src/main/scala/pca/PCACompBlock.scala:126:23
  reg  [12:0] multiplied_0_2;	// src/main/scala/pca/PCACompBlock.scala:126:23
  reg  [12:0] multiplied_0_3;	// src/main/scala/pca/PCACompBlock.scala:126:23
  reg  [12:0] multiplied_1_0;	// src/main/scala/pca/PCACompBlock.scala:126:23
  reg  [12:0] multiplied_1_1;	// src/main/scala/pca/PCACompBlock.scala:126:23
  reg  [12:0] multiplied_1_2;	// src/main/scala/pca/PCACompBlock.scala:126:23
  reg  [12:0] multiplied_1_3;	// src/main/scala/pca/PCACompBlock.scala:126:23
  reg  [15:0] partialcompressed_0;	// src/main/scala/pca/PCACompBlock.scala:127:30
  reg  [15:0] partialcompressed_1;	// src/main/scala/pca/PCACompBlock.scala:127:30
  reg  [16:0] compressedAccReg_0;	// src/main/scala/pca/PCACompBlock.scala:130:33
  reg  [16:0] compressedAccReg_1;	// src/main/scala/pca/PCACompBlock.scala:130:33
  reg  [31:0] compressedReg;	// src/main/scala/pca/PCACompBlock.scala:131:30
  reg         multipliedStageReg;	// src/main/scala/pca/PCACompBlock.scala:144:35
  reg         reducedStageReg;	// src/main/scala/pca/PCACompBlock.scala:145:35
  reg         enqOutQReg;	// src/main/scala/pca/PCACompBlock.scala:146:27
  reg         rowidDelayed_r;	// src/main/scala/pca/PCACompBlock.scala:155:35
  reg         rowidDelayed_r_1;	// src/main/scala/pca/PCACompBlock.scala:155:35
  reg         rowidDelayed;	// src/main/scala/pca/PCACompBlock.scala:155:35
  wire        _GEN = io_updateIEM | io_verifyIEM;	// src/main/scala/pca/PCACompBlock.scala:60:30, :100:22, :112:28, :117:26
  wire [16:0] _updatedAcc_0_T =
    compressedAccReg_0 + {partialcompressed_0[15], partialcompressed_0};	// src/main/scala/pca/PCACompBlock.scala:127:30, :130:33, :200:48
  wire [16:0] _updatedAcc_1_T =
    compressedAccReg_1 + {partialcompressed_1[15], partialcompressed_1};	// src/main/scala/pca/PCACompBlock.scala:127:30, :130:33, :200:48
  wire        _GEN_0 = reducedStageReg & rowidDelayed;	// src/main/scala/pca/PCACompBlock.scala:145:35, :155:35, :190:28, :194:25, :208:23, :210:32
  wire        _GEN_1 = _GEN_0 & reducedStageReg;	// src/main/scala/pca/PCACompBlock.scala:145:35, :190:28, :194:25, :208:23, :210:32
  wire [12:0] _GEN_2 = {8'h0, indataHoldReg[4:0]};	// src/main/scala/pca/PCACompBlock.scala:60:30, :61:41, :162:47
  wire [12:0] _GEN_3 = {8'h0, indataHoldReg[9:5]};	// src/main/scala/pca/PCACompBlock.scala:60:30, :61:41, :162:47
  wire [12:0] _GEN_4 = {8'h0, indataHoldReg[14:10]};	// src/main/scala/pca/PCACompBlock.scala:60:30, :61:41, :162:47
  wire [12:0] _GEN_5 = {8'h0, indataHoldReg[19:15]};	// src/main/scala/pca/PCACompBlock.scala:60:30, :61:41, :162:47
  wire [13:0] _partialcompressed_0_T =
    {multiplied_0_0[12], multiplied_0_0} + {multiplied_0_1[12], multiplied_0_1};	// src/main/scala/pca/PCACompBlock.scala:126:23, :173:58
  wire [14:0] _partialcompressed_0_T_1 =
    {_partialcompressed_0_T[13], _partialcompressed_0_T}
    + {{2{multiplied_0_2[12]}}, multiplied_0_2};	// src/main/scala/pca/PCACompBlock.scala:126:23, :173:58
  wire [13:0] _partialcompressed_1_T =
    {multiplied_1_0[12], multiplied_1_0} + {multiplied_1_1[12], multiplied_1_1};	// src/main/scala/pca/PCACompBlock.scala:126:23, :173:58
  wire [14:0] _partialcompressed_1_T_1 =
    {_partialcompressed_1_T[13], _partialcompressed_1_T}
    + {{2{multiplied_1_2[12]}}, multiplied_1_2};	// src/main/scala/pca/PCACompBlock.scala:126:23, :173:58
  always @(posedge clock) begin	// src/main/scala/pca/PCACompBlock.scala:11:7
    if (reset) begin	// src/main/scala/pca/PCACompBlock.scala:11:7
      indataHoldReg <= 20'h0;	// src/main/scala/pca/PCACompBlock.scala:60:30
      dataReceivedStageReg <= 1'h0;	// src/main/scala/pca/PCACompBlock.scala:63:20, :98:37
      compressedAccReg_0 <= 17'h0;	// src/main/scala/pca/PCACompBlock.scala:130:33
      compressedAccReg_1 <= 17'h0;	// src/main/scala/pca/PCACompBlock.scala:130:33
      compressedReg <= 32'h0;	// src/main/scala/pca/PCACompBlock.scala:131:30
      multipliedStageReg <= 1'h0;	// src/main/scala/pca/PCACompBlock.scala:63:20, :144:35
      reducedStageReg <= 1'h0;	// src/main/scala/pca/PCACompBlock.scala:63:20, :145:35
      enqOutQReg <= 1'h0;	// src/main/scala/pca/PCACompBlock.scala:63:20, :146:27
    end
    else begin	// src/main/scala/pca/PCACompBlock.scala:11:7
      if (_GEN | ~io_indatavalid) begin	// src/main/scala/pca/PCACompBlock.scala:60:30, :100:22, :112:28, :117:26
      end
      else	// src/main/scala/pca/PCACompBlock.scala:60:30, :100:22, :112:28, :117:26
        indataHoldReg <= io_indata;	// src/main/scala/pca/PCACompBlock.scala:60:30
      if (~_GEN)	// src/main/scala/pca/PCACompBlock.scala:60:30, :100:22, :112:28, :117:26
        dataReceivedStageReg <= io_indatavalid;	// src/main/scala/pca/PCACompBlock.scala:98:37
      if (reducedStageReg) begin	// src/main/scala/pca/PCACompBlock.scala:145:35
        compressedAccReg_0 <= rowidDelayed ? 17'h0 : _updatedAcc_0_T;	// src/main/scala/pca/PCACompBlock.scala:130:33, :155:35, :200:48, :208:23, :211:31, :214:31
        compressedAccReg_1 <= rowidDelayed ? 17'h0 : _updatedAcc_1_T;	// src/main/scala/pca/PCACompBlock.scala:130:33, :155:35, :200:48, :208:23, :211:31, :214:31
      end
      if (_GEN_0)	// src/main/scala/pca/PCACompBlock.scala:190:28, :194:25, :208:23, :210:32
        compressedReg <=
          {_GEN_1 ? _updatedAcc_1_T[15:0] : 16'h0,
           _GEN_1 ? _updatedAcc_0_T[15:0] : 16'h0};	// src/main/scala/pca/PCACompBlock.scala:131:30, :190:28, :194:25, :200:48, :208:23, :210:32, :221:50
      multipliedStageReg <= dataReceivedStageReg;	// src/main/scala/pca/PCACompBlock.scala:98:37, :144:35
      reducedStageReg <= multipliedStageReg;	// src/main/scala/pca/PCACompBlock.scala:144:35, :145:35
      enqOutQReg <= ~(enqOutQReg & _outQ_io_enq_ready) & (_GEN_0 | enqOutQReg);	// src/main/scala/pca/PCACompBlock.scala:146:27, :184:20, :190:28, :194:25, :208:23, :210:32, :219:21, :222:18, :228:20, :230:29, :236:18
    end
    multiplied_0_0 <=
      dataReceivedStageReg
        ? {{5{_mems_0_io_rdata[7]}}, _mems_0_io_rdata[7:0]} * _GEN_2
        : 13'h0;	// src/main/scala/pca/PCACompBlock.scala:70:11, :98:37, :126:23, :135:26, :141:43, :157:30, :162:{28,47}
    multiplied_0_1 <=
      dataReceivedStageReg
        ? {{5{_mems_0_io_rdata[15]}}, _mems_0_io_rdata[15:8]} * _GEN_3
        : 13'h0;	// src/main/scala/pca/PCACompBlock.scala:70:11, :98:37, :126:23, :135:26, :141:43, :157:30, :162:{28,47}
    multiplied_0_2 <=
      dataReceivedStageReg
        ? {{5{_mems_0_io_rdata[23]}}, _mems_0_io_rdata[23:16]} * _GEN_4
        : 13'h0;	// src/main/scala/pca/PCACompBlock.scala:70:11, :98:37, :126:23, :135:26, :141:43, :157:30, :162:{28,47}
    multiplied_0_3 <=
      dataReceivedStageReg
        ? {{5{_mems_0_io_rdata[31]}}, _mems_0_io_rdata[31:24]} * _GEN_5
        : 13'h0;	// src/main/scala/pca/PCACompBlock.scala:70:11, :98:37, :126:23, :135:26, :141:43, :157:30, :162:{28,47}
    multiplied_1_0 <=
      dataReceivedStageReg
        ? {{5{_mems_1_io_rdata[7]}}, _mems_1_io_rdata[7:0]} * _GEN_2
        : 13'h0;	// src/main/scala/pca/PCACompBlock.scala:70:11, :98:37, :126:23, :135:26, :141:43, :157:30, :162:{28,47}
    multiplied_1_1 <=
      dataReceivedStageReg
        ? {{5{_mems_1_io_rdata[15]}}, _mems_1_io_rdata[15:8]} * _GEN_3
        : 13'h0;	// src/main/scala/pca/PCACompBlock.scala:70:11, :98:37, :126:23, :135:26, :141:43, :157:30, :162:{28,47}
    multiplied_1_2 <=
      dataReceivedStageReg
        ? {{5{_mems_1_io_rdata[23]}}, _mems_1_io_rdata[23:16]} * _GEN_4
        : 13'h0;	// src/main/scala/pca/PCACompBlock.scala:70:11, :98:37, :126:23, :135:26, :141:43, :157:30, :162:{28,47}
    multiplied_1_3 <=
      dataReceivedStageReg
        ? {{5{_mems_1_io_rdata[31]}}, _mems_1_io_rdata[31:24]} * _GEN_5
        : 13'h0;	// src/main/scala/pca/PCACompBlock.scala:70:11, :98:37, :126:23, :135:26, :141:43, :157:30, :162:{28,47}
    partialcompressed_0 <=
      multipliedStageReg
        ? {_partialcompressed_0_T_1[14], _partialcompressed_0_T_1}
          + {{3{multiplied_0_3[12]}}, multiplied_0_3}
        : 16'h0;	// src/main/scala/pca/PCACompBlock.scala:126:23, :127:30, :137:28, :144:35, :170:28, :173:{30,58}
    partialcompressed_1 <=
      multipliedStageReg
        ? {_partialcompressed_1_T_1[14], _partialcompressed_1_T_1}
          + {{3{multiplied_1_3[12]}}, multiplied_1_3}
        : 16'h0;	// src/main/scala/pca/PCACompBlock.scala:126:23, :127:30, :137:28, :144:35, :170:28, :173:{30,58}
    rowidDelayed_r <= io_rowid;	// src/main/scala/pca/PCACompBlock.scala:155:35
    rowidDelayed_r_1 <= rowidDelayed_r;	// src/main/scala/pca/PCACompBlock.scala:155:35
    rowidDelayed <= rowidDelayed_r_1;	// src/main/scala/pca/PCACompBlock.scala:155:35
  end // always @(posedge)
  SRAM1RW__depth2_width32_simulation mems_0 (	// src/main/scala/pca/PCACompBlock.scala:70:11
    .clock    (clock),
    .io_we    (io_updateIEM & ~io_iempos),	// src/main/scala/pca/PCACompBlock.scala:73:19, :100:22, :102:{22,31}
    .io_addr  (io_rowid),
    .io_wdata (io_updateIEM & ~io_iempos ? io_iemdata : 32'h0),	// src/main/scala/pca/PCACompBlock.scala:75:22, :100:22, :102:{22,31}, :106:26
    .io_rdata (_mems_0_io_rdata)
  );	// src/main/scala/pca/PCACompBlock.scala:70:11
  SRAM1RW__depth2_width32_simulation mems_1 (	// src/main/scala/pca/PCACompBlock.scala:70:11
    .clock    (clock),
    .io_we    (io_updateIEM & io_iempos),	// src/main/scala/pca/PCACompBlock.scala:73:19, :100:22, :102:31
    .io_addr  (io_rowid),
    .io_wdata (io_updateIEM & io_iempos ? io_iemdata : 32'h0),	// src/main/scala/pca/PCACompBlock.scala:75:22, :100:22, :102:31, :106:26
    .io_rdata (_mems_1_io_rdata)
  );	// src/main/scala/pca/PCACompBlock.scala:70:11
  Queue4_UInt32 outQ (	// src/main/scala/pca/PCACompBlock.scala:184:20
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_outQ_io_enq_ready),
    .io_enq_valid (enqOutQReg & _outQ_io_enq_ready),	// src/main/scala/pca/PCACompBlock.scala:146:27, :184:20, :227:21, :228:20, :230:29
    .io_enq_bits  (compressedReg),	// src/main/scala/pca/PCACompBlock.scala:131:30
    .io_deq_ready (io_out_ready),
    .io_deq_valid (io_out_valid),
    .io_deq_bits  (io_out_bits)
  );	// src/main/scala/pca/PCACompBlock.scala:184:20
  assign io_iemdataverify =
    io_updateIEM | ~io_verifyIEM
      ? 32'h0
      : io_iempos ? _mems_1_io_rdata : _mems_0_io_rdata;	// src/main/scala/pca/PCACompBlock.scala:11:7, :70:11, :82:15, :100:22, :112:28, :113:17
endmodule


