// Generated by CIRCT firtool-1.138.0
module PCACompMMIOBridge(	// src/main/scala/pca/PCACompMMIOBridge.scala:22:7
  input         clock,	// src/main/scala/pca/PCACompMMIOBridge.scala:22:7
                reset,	// src/main/scala/pca/PCACompMMIOBridge.scala:22:7
  input  [31:0] io_mmio_addr,	// src/main/scala/pca/PCACompMMIOBridge.scala:25:14
                io_mmio_wdata,	// src/main/scala/pca/PCACompMMIOBridge.scala:25:14
  input         io_mmio_wen,	// src/main/scala/pca/PCACompMMIOBridge.scala:25:14
  output [31:0] io_mmio_rdata	// src/main/scala/pca/PCACompMMIOBridge.scala:25:14
);

  wire        _block_io_out_valid;	// src/main/scala/pca/PCACompMMIOBridge.scala:23:21
  wire [31:0] _block_io_out_bits;	// src/main/scala/pca/PCACompMMIOBridge.scala:23:21
  wire [31:0] _block_io_iemdataverify;	// src/main/scala/pca/PCACompMMIOBridge.scala:23:21
  reg  [3:0]  ctrl;	// src/main/scala/pca/PCACompMMIOBridge.scala:55:21
  reg         rowid;	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22
  reg         iempos;	// src/main/scala/pca/PCACompMMIOBridge.scala:57:23
  reg  [31:0] iemdata;	// src/main/scala/pca/PCACompMMIOBridge.scala:58:24
  reg  [19:0] indata;	// src/main/scala/pca/PCACompMMIOBridge.scala:59:23
  wire        read_result = io_mmio_addr == 32'h18;	// src/main/scala/pca/PCACompMMIOBridge.scala:71:34
  wire        _GEN = io_mmio_addr == 32'h0;	// src/main/scala/pca/PCACompMMIOBridge.scala:58:24, :62:26
  wire        _GEN_0 = io_mmio_addr == 32'h4;	// src/main/scala/pca/PCACompMMIOBridge.scala:62:26
  wire        _GEN_1 = io_mmio_addr == 32'h8;	// src/main/scala/pca/PCACompMMIOBridge.scala:62:26
  wire        _GEN_2 = io_mmio_addr == 32'hC;	// src/main/scala/pca/PCACompMMIOBridge.scala:62:26
  always @(posedge clock) begin	// src/main/scala/pca/PCACompMMIOBridge.scala:22:7
    if (reset) begin	// src/main/scala/pca/PCACompMMIOBridge.scala:22:7
      ctrl <= 4'h0;	// src/main/scala/pca/PCACompMMIOBridge.scala:55:21
      rowid <= 1'h0;	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22
      iempos <= 1'h0;	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22, :57:23
      iemdata <= 32'h0;	// src/main/scala/pca/PCACompMMIOBridge.scala:58:24
      indata <= 20'h0;	// src/main/scala/pca/PCACompMMIOBridge.scala:59:23
    end
    else begin	// src/main/scala/pca/PCACompMMIOBridge.scala:22:7
      if (io_mmio_wen & _GEN)	// src/main/scala/pca/PCACompMMIOBridge.scala:55:21, :61:21, :62:26, :63:31
        ctrl <= io_mmio_wdata[3:0];	// src/main/scala/pca/PCACompMMIOBridge.scala:55:21, :63:47
      if (~io_mmio_wen | _GEN | ~_GEN_0) begin	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22, :61:21, :62:26
      end
      else	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22, :61:21, :62:26
        rowid <= io_mmio_wdata[0];	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22, :64:48
      if (~io_mmio_wen | _GEN | _GEN_0 | ~_GEN_1) begin	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22, :57:23, :61:21, :62:26
      end
      else	// src/main/scala/pca/PCACompMMIOBridge.scala:57:23, :61:21, :62:26
        iempos <= io_mmio_wdata[0];	// src/main/scala/pca/PCACompMMIOBridge.scala:57:23, :65:49
      if (~io_mmio_wen | _GEN | _GEN_0 | _GEN_1 | ~_GEN_2) begin	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22, :58:24, :61:21, :62:26
      end
      else	// src/main/scala/pca/PCACompMMIOBridge.scala:58:24, :61:21, :62:26
        iemdata <= io_mmio_wdata;	// src/main/scala/pca/PCACompMMIOBridge.scala:58:24
      if (~io_mmio_wen | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | io_mmio_addr != 32'h10) begin	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22, :59:23, :61:21, :62:26
      end
      else	// src/main/scala/pca/PCACompMMIOBridge.scala:59:23, :61:21, :62:26
        indata <= io_mmio_wdata[19:0];	// src/main/scala/pca/PCACompMMIOBridge.scala:59:23, :67:49
    end
  end // always @(posedge)
  PCACompBlock_nrows2_ncols12_nblocks3_w4_pxbw5_iembw8_npcs2 block (	// src/main/scala/pca/PCACompMMIOBridge.scala:23:21
    .clock            (clock),
    .reset            (reset),
    .io_rowid         (rowid),	// src/main/scala/pca/PCACompMMIOBridge.scala:56:22
    .io_indata        (indata),	// src/main/scala/pca/PCACompMMIOBridge.scala:59:23
    .io_indatavalid   (ctrl[2]),	// src/main/scala/pca/PCACompMMIOBridge.scala:55:21, :74:31
    .io_out_ready     (read_result),	// src/main/scala/pca/PCACompMMIOBridge.scala:71:34
    .io_out_valid     (_block_io_out_valid),
    .io_out_bits      (_block_io_out_bits),
    .io_updateIEM     (ctrl[0]),	// src/main/scala/pca/PCACompMMIOBridge.scala:55:21, :75:29
    .io_verifyIEM     (ctrl[1]),	// src/main/scala/pca/PCACompMMIOBridge.scala:55:21, :76:29
    .io_iempos        (iempos),	// src/main/scala/pca/PCACompMMIOBridge.scala:57:23
    .io_iemdata       (iemdata),	// src/main/scala/pca/PCACompMMIOBridge.scala:58:24
    .io_iemdataverify (_block_io_iemdataverify)
  );	// src/main/scala/pca/PCACompMMIOBridge.scala:23:21
  assign io_mmio_rdata =
    io_mmio_addr == 32'h14
      ? {31'h0, _block_io_out_valid}
      : read_result
          ? _block_io_out_bits
          : io_mmio_addr == 32'h1C ? _block_io_iemdataverify : 32'h0;	// src/main/scala/pca/PCACompMMIOBridge.scala:22:7, :23:21, :58:24, :71:34, :81:19, :88:{18,32}, :89:17, :90:{17,31}
endmodule


