// Generated by CIRCT firtool-1.138.0
module Queue4_UInt32(	// src/main/scala/chisel3/util/Queue.scala:60:7
  input         clock,	// src/main/scala/chisel3/util/Queue.scala:60:7
                reset,	// src/main/scala/chisel3/util/Queue.scala:60:7
  output        io_enq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_enq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input  [31:0] io_enq_bits,	// src/main/scala/chisel3/util/Queue.scala:72:14
  input         io_deq_ready,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output        io_deq_valid,	// src/main/scala/chisel3/util/Queue.scala:72:14
  output [31:0] io_deq_bits	// src/main/scala/chisel3/util/Queue.scala:72:14
);

  reg  [1:0] enq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg  [1:0] deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40
  reg        maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27
  wire       ptr_match = enq_ptr_value == deq_ptr_value;	// src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Queue.scala:77:33
  wire       empty = ptr_match & ~maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :78:{25,28}
  wire       full = ptr_match & maybe_full;	// src/main/scala/chisel3/util/Queue.scala:76:27, :77:33, :79:24
  wire       do_enq = ~full & io_enq_valid;	// src/main/scala/chisel3/util/Queue.scala:79:24, :103:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire       do_deq = io_deq_ready & ~empty;	// src/main/scala/chisel3/util/Queue.scala:78:25, :102:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
    if (reset) begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      enq_ptr_value <= 2'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      deq_ptr_value <= 2'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
      maybe_full <= 1'h0;	// src/main/scala/chisel3/util/Queue.scala:76:27
    end
    else begin	// src/main/scala/chisel3/util/Queue.scala:60:7
      if (do_enq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        enq_ptr_value <= enq_ptr_value + 2'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_deq)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        deq_ptr_value <= deq_ptr_value + 2'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
      if (do_enq != do_deq)	// src/main/scala/chisel3/util/Queue.scala:76:27, :93:{15,27}, :94:16, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
        maybe_full <= do_enq;	// src/main/scala/chisel3/util/Queue.scala:76:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    end
  end // always @(posedge)
  ram_4x32 ram_ext (	// src/main/scala/chisel3/util/Queue.scala:73:91
    .R0_addr (deq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .R0_en   (1'h1),	// src/main/scala/chisel3/util/Queue.scala:60:7
    .R0_clk  (clock),
    .R0_data (io_deq_bits),
    .W0_addr (enq_ptr_value),	// src/main/scala/chisel3/util/Counter.scala:61:40
    .W0_en   (do_enq),	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    .W0_clk  (clock),
    .W0_data (io_enq_bits)
  );	// src/main/scala/chisel3/util/Queue.scala:73:91
  assign io_enq_ready = ~full;	// src/main/scala/chisel3/util/Queue.scala:60:7, :79:24, :103:19
  assign io_deq_valid = ~empty;	// src/main/scala/chisel3/util/Queue.scala:60:7, :78:25, :102:19
endmodule


