// Generated by CIRCT firtool-1.138.0
// VCS coverage exclude_file
module ram_4x32(	// src/main/scala/chisel3/util/Queue.scala:73:91
  input  [1:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [1:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:3];	// src/main/scala/chisel3/util/Queue.scala:73:91
  always @(posedge W0_clk) begin	// src/main/scala/chisel3/util/Queue.scala:73:91
    if (W0_en)	// src/main/scala/chisel3/util/Queue.scala:73:91
      Memory[W0_addr] <= W0_data;	// src/main/scala/chisel3/util/Queue.scala:73:91
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/chisel3/util/Queue.scala:73:91
endmodule


