// Generated by CIRCT firtool-1.138.0
module SRAM1RW__depth2_width32_simulation(	// src/main/scala/pca/SRAM1RW.scala:11:7
  input         clock,	// src/main/scala/pca/SRAM1RW.scala:11:7
                io_we,	// src/main/scala/pca/SRAM1RW.scala:12:14
                io_addr,	// src/main/scala/pca/SRAM1RW.scala:12:14
  input  [31:0] io_wdata,	// src/main/scala/pca/SRAM1RW.scala:12:14
  output [31:0] io_rdata	// src/main/scala/pca/SRAM1RW.scala:12:14
);

  mem_2x32 mem_ext (	// src/main/scala/pca/SRAM1RW.scala:26:26
    .R0_addr (io_addr),
    .R0_en   (1'h1),	// src/main/scala/pca/SRAM1RW.scala:11:7
    .R0_clk  (clock),
    .R0_data (io_rdata),
    .W0_addr (io_addr),
    .W0_en   (io_we),
    .W0_clk  (clock),
    .W0_data (io_wdata)
  );	// src/main/scala/pca/SRAM1RW.scala:26:26
endmodule


